# .bash_profile

[ -f ~/.env ] && . ~/.env
[ -f ~/.fun ] && . ~/.fun

if [ "$ID" = debian ]; then
    eval $(dircolors -b <(dircolors -p))
fi

stty -ixon

# https://wiki.gentoo.org/wiki/X_without_Display_Manager
# https://wiki.gentoo.org/wiki/Start_X_on_login
if [ -z "$DISPLAY" -a "$(tty)" = /dev/tty1 ]; then
	exec startx
	#exec i3
	#exec sway
fi
