# .bashrc

# Source global definitions
# Fedora
[ -f /etc/bashrc ] && . /etc/bashrc
# Debian
[ -f /etc/bash.bashrc ] && . /etc/bash.bashrc

# Fedora /etc/bashrc will source /etc/profile.d/*.sh
# and some of them will set aliases
unalias -a
stty -ixon
