# .bashrc

# Source global definitions
# Fedora
# [ -f /etc/bashrc ] && . /etc/bashrc
# Debian
# On debian /etc/profile try to change my PATH,
# and /etc/bash.bashrc try to change my PS1. WTF!
# /etc/bash.bashrc won't source /etc/profile.d/*.sh
# /etc/profile will do
# [ -f /etc/profile ] && . /etc/profile

# Only display echos from profile.d scripts if we are no login shell
# and interactive - otherwise just process them to set envvars
for i in /etc/profile.d/*.sh; do
	if [ -r "$i" ]; then
		if [ "$PS1" ]; then
			. "$i"
		else
			. "$i" >/dev/null
		fi
	fi
done
unset i

# Avoid scp error "stty: 'standard input': Inappropriate ioctl for device"
# [ "$SHLVL" -le 2 ] && stty -ixon
#if [ -z "$STY" -a -z "$SSH_TTY" -a -n "$PS1" ]; then
if [[ $- == *i* && -t 0 ]]; then
	stty -ixon # Disable Ctrl-S / Ctrl-Q flow control
fi

# if [ -n "$PS1" ]; then # -n $PS1 unreliable
if [[ $- == *i* && -z ${__MY_COMPLETIONS_LOADED:-} ]]; then
    __MY_COMPLETIONS_LOADED=1

    # re-use completions
    _completion_loader git
    complete -o bashdefault -o default -o nospace -F __git_wrap__git_main g
    _completion_loader man
    complete -F _comp_cmd_man m
    _completion_loader systemctl
    complete -F _systemctl sd
    _completion_loader cargo
    complete -F _cargo c
fi

# man gpg-agent
GPG_TTY=$(tty)

#if [ -z "$STY" ]; then
#    screen -R
#fi

[ -f ~/.env ] && . ~/.env
[ -f ~/.fun ] && . ~/.fun
[ -f ~/.env.override ] && . ~/.env.override
