#!/bin/bash
# vim:ft=sh

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# fnm
FNM_PATH="/home/al/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
  # eval "$(fnm env --use-on-cd)"
fi

# # nvm
# export NVM_DIR="$HOME/.nvm"
# [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
# [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# deno
#. "/home/al/.deno/env"
#source /home/al/.local/share/bash-completion/completions/deno.bash
