#!/bin/bash
# vim:ft=sh

[ -f "$HOME/.cargo/env" ] && . "$HOME/.cargo/env"

# fnm
FNM_PATH="/home/al/.local/share/fnm"
if [ -d "$FNM_PATH" ]; then
  export PATH="$FNM_PATH:$PATH"
  eval "`fnm env`"
  # eval "$(fnm env --use-on-cd)"
fi
