#!/bin/bash
#
# vim:ft=sh
# Run by startx

# Since we don't use urxvt anymore
# userresources=$HOME/.Xresources
# [ -r "$userresources" ] && xrdb -merge "$userresources"

[ -x ~/.monitors.sh ] && ~/.monitors.sh

exec i3
