[font.normal]
family = "Liberation Mono"
style = "regular"

[window]
#decorations = "none"
startup_mode = "Maximized" #"Fullscreen"
opacity = 0.6

[env]
TERM = "xterm-256color" # alacritty will override TERM, so set it here
