# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

# the rest of the config defines the layers with their bindings
layers:
  # the first layer is active at start
  - name: initial
    bindings:
      # when tab is held and another key pressed, activate mouse layer
      #tab: tap-hold-next tab ; toggle-layer mouse ; 500
      # when a is held for 300ms, activate mouse layer
      capslock: tap-hold capslock ; toggle-layer mouse ; 300
  # a layer for mouse movement
  - name: mouse
    # when true, keys that are not mapped keep their original meaning
    passThrough: true
    enterCommand: "notify-send -t 1000 'mouse layer entered'"
    exitCommand: "notify-send -u low -t 1000 'mouse layer exited'"
    bindings:
      # quit mouse layer
      q: layer initial
      # r: reload-config
      # keep the mouse layer active
      a: layer mouse
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      o: button left
      i: button right
      dot: button left
      comma: button right
      semicolon: tap-hold e; toggle-layer scroll; 100
      space: speed 0.2
      leftalt: speed 4
      #_: layer initial

  - name: scroll
    bindings:
      j: scroll down
      k: scroll up
      h: scroll left
      l: scroll right
