# the default speed for mouse movement and scrolling
baseMouseSpeed: 750.0
baseScrollSpeed: 20.0

# the rest of the config defines the layers with their bindings
layers:
  # the first layer is active at start
  - name: initial
    bindings:
      # when tab is held and another key pressed, activate mouse layer
      #tab: tap-hold-next tab ; toggle-layer mouse ; 500
      # when a is held for 300ms, activate mouse layer
      capslock: tap-hold capslock ; toggle-layer mouse ; 500
  # a layer for mouse movement
  - name: mouse
    # when true, keys that are not mapped keep their original meaning
    passThrough: true
    bindings:
      # quit mouse layer
      q: layer initial
      # keep the mouse layer active
      space: layer mouse
      l: move  1  0
      h: move -1  0
      j: move  0  1
      k: move  0 -1
      y: move  -1 -1
      u: move  -1 -1
      o: move  1 -1
      n: move  -1 1
      m: move  1 1
      i: scroll up
      comma: scroll down
      leftalt: speed 4.0
      e: speed 0.2
      #capslock: speed 0.1
      f: button left
      d: button right
      s: button middle
