# =========================
# name.itove.com (HTTP → HTTPS)
# =========================
server {
    listen 80;
    server_name name.itove.com www.name.com;

    return 301 https://$host$request_uri;
}

# =========================
# name.itove.com (HTTPS)
# =========================
server {
    listen 443 ssl;
    server_name name.itove.com www.name.com;

    root /home/al/w/name/public;
    index index.php;

    access_log /var/log/nginx/name_access.log;
    error_log  /var/log/nginx/name_error.log;

    ssl_certificate     /home/al/cert/name.itove.com.fullchain.cer;
    ssl_certificate_key /home/al/cert/name.itove.com.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL;
    ssl_prefer_server_ciphers on;

    # Symfony front controller
    location / {
        try_files $uri /index.php$is_args$args;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock; # adjust if needed
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;
    }
}

# =========================
# name2.itove.com (HTTP → HTTPS)
# =========================
server {
    listen 80;
    server_name name2.itove.com www.name2.com;

    return 301 https://$host$request_uri;
}

# =========================
# name2.itove.com (HTTPS)
# =========================
server {
    listen 443 ssl;
    server_name name2.itove.com www.name2.com;

    root /home/al/w/name2/public;
    index index.php;

    access_log /var/log/nginx/name2_access.log;
    error_log  /var/log/nginx/name2_error.log;

    ssl_certificate     /home/al/cert/name2.itove.com.fullchain.cer;
    ssl_certificate_key /home/al/cert/name2.itove.com.key;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL;
    ssl_prefer_server_ciphers on;

    location / {
        try_files $uri /index.php$is_args$args;
    }

    location = /favicon.ico {
        log_not_found off;
        access_log off;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass unix:/run/php/php-fpm.sock; # adjust if needed
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        fastcgi_param DOCUMENT_ROOT $realpath_root;
    }

    location ~ /\.ht {
        deny all;
    }
}
